{% set name = "authlib" %}
{% set version = "1.7.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  - url: https://github.com/authlib/{{ name }}/archive/refs/tags/v{{ version }}.tar.gz
    sha256: 939d7d4c1ea10e3747b03cc76c478f5158657a32645a496be38100c927ee6a4c

build:
  skip: true  # [py<310]
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps --no-build-isolation --ignore-installed --no-cache-dir -vv

requirements:
  host:
    - python
    - pip
    - setuptools
    - wheel
  run:
    - python
    # Keep requests at runtime for backward compatibility
    - requests
    - cryptography
    - joserfc >=1.6.0
  run_constrained:
    - pycryptodomex >=3.10,<4

# AssertionError: assert 'dev' == 'dev-client-id'
{% set tests_to_skip = "test_register_with_overwrite" %}
# Exclude django: django.core.exceptions.AppRegistryNotReady: Apps aren't loaded yet
{% set ignore_tests = "--ignore=tests/django" %}

test:
  source_files:
    - tests
    - pyproject.toml
  imports:
    - authlib
    - authlib.consts
    - authlib.common
    - authlib.integrations
    - authlib.jose
    - authlib.oauth1
    - authlib.oauth2
    - authlib.oidc
  requires:
    - pip
    - pytest
    - pytest-asyncio
    - python-multipart
    - flask
    - flask-sqlalchemy
    - django
    - cachelib
    - httpx
    - starlette
  commands:
    - pip check
    - python -c "from importlib.metadata import version; assert(version('{{ name }}')=='{{ version }}')"
    - set DJANGO_SETTINGS_MODULE=tests.django_settings  # [win]
    - export DJANGO_SETTINGS_MODULE=tests.django_settings  # [unix]
    - pytest -v tests {{ ignore_tests }} -k "not {{ tests_to_skip }}"

about:
  home: https://authlib.org
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: The ultimate Python library in building OAuth and OpenID Connect servers. JWS,JWE,JWK,JWA,JWT included. https://authlib.org
  description: |
    The ultimate Python library in building OAuth and OpenID Connect servers.
    It is designed from low level specifications implementations to high level frameworks integrations,
    to meet the needs of everyone.
  doc_url: https://docs.authlib.org
  dev_url: https://github.com/authlib/authlib

extra:
  recipe-maintainers:
    - chrisburr
    - markfennema