{% set name = "authlib" %}
{% set version = "1.6.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 4367d32031b7af175ad3a323d571dc7257b7099d55978087ceae4a0d88cd3210
  url: https://github.com/authlib/{{ name }}/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 2dfc1275b287aa1324ac5c014766b8c79fb228c59d98c021750d86b6ec7e0904

build:
  skip: true  # [py<39]
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps --no-build-isolation --ignore-installed --no-cache-dir -vv

requirements:
  host:
    - python
    - pip
    - setuptools
    - wheel
  run:
    - python
    # Keep requests at runtime for backward compatibility
    - requests
    - cryptography >=3.2
  run_constrained:
    - pycryptodomex >=3.10,<4
    - asgiref==3.6.0   # [py<310 and python_impl=="pypy"]

# AssertionError: assert 'dev' == 'dev-client-id'
{% set tests_to_skip = "test_register_with_overwrite" %}
# Exclude django: django.core.exceptions.AppRegistryNotReady: Apps aren't loaded yet
{% set ignore_tests = "--ignore=tests/django" %}

test:
  source_files:
    - tests
  imports:
    - authlib
    - authlib.consts
    - authlib.common
    - authlib.integrations
    - authlib.jose
    - authlib.oauth1
    - authlib.oauth2
    - authlib.oidc
  requires:
    - pip
    - pytest
    - pytest-asyncio
    - pytest-tornasync
    - flask
    - flask-sqlalchemy
    - django
    - cachelib
    - httpx
    - starlette
  commands:
    - pip check
    - python -c "from importlib.metadata import version; assert(version('{{ name }}')=='{{ version }}')"
    - export DJANGO_SETTINGS_MODULE=tests.django.settings
    - pytest -v tests {{ ignore_tests }} -k "not {{ tests_to_skip }}"

about:
  home: https://authlib.org
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: The ultimate Python library in building OAuth and OpenID Connect servers. JWS,JWE,JWK,JWA,JWT included. https://authlib.org
  description: |
    The ultimate Python library in building OAuth and OpenID Connect servers.
    It is designed from low level specifications implementations to high level frameworks integrations,
    to meet the needs of everyone.
  doc_url: https://docs.authlib.org
  dev_url: https://github.com/lepture/authlib

extra:
  recipe-maintainers:
    - chrisburr
    - markfennema