{% set name = "authlib" %}
{% set version = "1.8.0" %}
{% set tests_to_skip = "test_register_with_overwrite" %}
{% set ignore_tests = "--ignore=tests/django" %}

# AssertionError: assert 'dev' == 'dev-client-id'
# Exclude django: django.core.exceptions.AppRegistryNotReady: Apps aren't loaded yet
package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  - url: https://github.com/authlib/{{ name }}/archive/refs/tags/v{{ version }}.tar.gz
    sha256: 216e3085ff2b371100acbb7e8a3bfe6e403ac138dababb3346b6147c3564ca56

build:
  skip: true  # [py<310]
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps --no-build-isolation --ignore-installed --no-cache-dir -vv

requirements:
  host:
    - python
    - pip
    - setuptools
    - wheel
  run:
    - python
    # Keep requests at runtime for backward compatibility
    - requests
    - cryptography >=45.0.1
    - joserfc >=1.6.1
  run_constrained:
    - pycryptodomex >=3.10,<4

test:
  source_files:
    - tests
    - pyproject.toml
  imports:
    - authlib
    - authlib.consts
    - authlib.common
    - authlib.integrations
    - authlib.jose
    - authlib.oauth1
    - authlib.oauth2
    - authlib.oidc
  requires:
    - pip
    - pytest
    - pytest-asyncio
    - python-multipart
    - flask
    - flask-sqlalchemy
    - django
    - cachelib
    - httpx
    - starlette
  commands:
    - pip check
    - python -c "from importlib.metadata import version; assert(version('{{ name }}')=='{{ version }}')"
    - set DJANGO_SETTINGS_MODULE=tests.django_settings  # [win]
    - export DJANGO_SETTINGS_MODULE=tests.django_settings  # [unix]
    - pytest -v tests {{ ignore_tests }} -k "not {{ tests_to_skip }}"

about:
  home: https://authlib.org
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: The ultimate Python library in building OAuth and OpenID Connect servers. JWS,JWE,JWK,JWA,JWT included. https://authlib.org
  description: |
    The ultimate Python library in building OAuth and OpenID Connect servers.
    It is designed from low level specifications implementations to high level frameworks integrations,
    to meet the needs of everyone.
  doc_url: https://docs.authlib.org
  dev_url: https://github.com/authlib/authlib

extra:
  recipe-maintainers:
    - chrisburr
    - markfennema
