travis:
  secure:
    BINSTAR_TOKEN: R0dbYqHxC3sXXgcYpNOVCG87Dh2m9VFXBnVp0aGZobTxzyQSY75Ko4S4p+KsKQqn7E2+ONKvKM2Ls/xDkToo/5Ms+MGhk4LXsvn5/gqxQAjWL67/TXm7PlR6JOUbk97QMlhDLkqFUCKCR78r6wJUNRecYIzizkOutITGYIknOIsUMSg9ErGoSZYHwhuxLwsuLJljyXcIfkblP6Tz12fvEROlXCux8IotuVOuhcy5rK/BQMTqZ3ND0mUEr4ytB2dvPQLTHI6owUlr+DpMt7XqsRwONn/J1ZL5cgstnFloRTNaD74LvGHRAnGiQz7qGq+rD3Rsh1FdY1jC/d4Xd+uvMNV+193T2fQ1dlxFIy26ff2QiUsZb0HuYJxoqQDmUs4Df+su07vNA5xm94JMiDW02bZuxf3vpnv9HvQz2wXQJud2F9bCbd7j/vVu4u7rQiNwZJda3pDUVcPuKcPavf8jS+oTw0jtTh3EyWv+wMaogRTW7SDeC/7K2wZ0CCsHM7HJDHUtw8QhvyCvScfzO/NKK3rzEiaN1ECwXDxFAxMEBzJenSeElPrsIgJtWlT8tVM1PqT1eN8Cj5tBNbzgOhSCZAn0OklMqtb7KEFn6s5I2qkNorRYmIauHgj2Vq/kjFz32iVSKbac+E8famKrafGcKySoiWA6dIP7+ka4vyDvYPI=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
